'use client'
// Dados mockados para o protótipo — será substituído por queries Supabase na Etapa 3

import { Game, Arena, Post, SportKey } from '@/lib/types'

export const MOCK_ARENAS: Arena[] = [
  {
    id: 'arena-faro-beach',
    name: 'Arena Faro Beach',
    address: 'Praia de Faro, 8000-139',
    city: 'Faro',
    latitude: 37.0194,
    longitude: -7.9322,
    sports: ['futevolei', 'beach_tenis', 'volei'],
    is_pro: true,
    price_per_hour: 15,
    rating: 4.8,
    total_reviews: 124,
    images: [],
    amenities: ['🚿 Vestiário', '🅿️ Estacionamento', '🥤 Lanchonete', '💡 Iluminação'],
    phone: '+351 289 000 001',
    website: 'www.arenafarobeach.pt',
    status: 'ativa',
    owner_id: 'user-arena-001',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sport-center-algarve',
    name: 'Sport Center Algarve',
    address: 'Rua Desportiva 45',
    city: 'Faro',
    latitude: 37.0150,
    longitude: -7.9290,
    sports: ['beach_tenis', 'volei'],
    is_pro: false,
    price_per_hour: 8,
    rating: 4.3,
    total_reviews: 67,
    images: [],
    amenities: ['🚿 Vestiário', '🅿️ Estacionamento'],
    status: 'ativa',
    owner_id: 'user-arena-002',
    created_at: new Date().toISOString(),
  },
]

export const MOCK_GAMES: Game[] = [
  {
    id: 'game-001',
    title: 'Pelada na Praia — Faro',
    sport: 'futevolei',
    arena_id: 'arena-faro-beach',
    created_by: 'user-001',
    players: ['user-001', 'user-002', 'user-003'],
    max_players: 4,
    date: new Date().toISOString().split('T')[0],
    start_time: '18:00',
    duration_minutes: 90,
    price: 0,
    level: 'todos',
    status: 'open',
    created_at: new Date().toISOString(),
  },
  {
    id: 'game-002',
    title: 'Duelo do Algarve',
    sport: 'beach_tenis',
    arena_id: 'sport-center-algarve',
    created_by: 'user-002',
    players: ['user-002', 'user-003', 'user-004'],
    max_players: 4,
    date: new Date().toISOString().split('T')[0],
    start_time: '19:00',
    duration_minutes: 120,
    price: 5,
    level: 'intermediario',
    status: 'open',
    created_at: new Date().toISOString(),
  },
  {
    id: 'game-003',
    title: 'Vôlei de Praia — Sunset',
    sport: 'volei',
    arena_id: 'arena-faro-beach',
    created_by: 'user-003',
    players: ['user-003', 'user-004', 'user-005', 'user-006'],
    max_players: 6,
    date: new Date().toISOString().split('T')[0],
    start_time: '19:30',
    duration_minutes: 120,
    price: 0,
    level: 'todos',
    status: 'open',
    created_at: new Date().toISOString(),
  },
]

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-001',
    author_id: 'user-ricardo',
    author: {
      id: 'user-ricardo',
      name: 'Ricardo Melo',
      email: 'ricardo@playhub.pt',
      type: 'atleta',
      sports: [{ key: 'futevolei', name: 'Futevôlei', icon: '🏖️' }],
      created_at: new Date().toISOString(),
    },
    text: 'Treino de manhã na Praia de Faro com a equipa. A areia estava perfeita e o vento ajudou muito. Quem quiser juntar-se amanhã às 8h é só aparecer! 🌊',
    sport: 'futevolei',
    media_type: 'photo',
    likes: ['user-001', 'user-002', 'user-003'],
    comments_count: 8,
    created_at: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: 'post-002',
    author_id: 'arena-faro-beach',
    author: {
      id: 'arena-faro-beach',
      name: 'Arena Faro Beach',
      email: 'arena@farob.pt',
      type: 'empresa',
      sports: [],
      empresa_status: 'aprovado',
      created_at: new Date().toISOString(),
    },
    text: 'Novos horários disponíveis para esta semana! Beach Tênis e Futevôlei com iluminação nocturna até às 22h. Reserve já pelo PlayHub. ⚡',
    sport: 'beach_tenis',
    media_type: 'none',
    likes: ['user-001', 'user-002'],
    comments_count: 12,
    created_at: new Date(Date.now() - 60 * 60000).toISOString(),
  },
]

export function useMockData() {
  return { arenas: MOCK_ARENAS, games: MOCK_GAMES, posts: MOCK_POSTS }
}
